#cloud-config

apt:
  sources:
    postgresql.list:
      source: "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main"
      keyid: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

write_files:
  - path: /etc/environment
    content: |
      SESSION_KEY=${session_encoder_key}
    append: true
  - path: /etc/systemd/system/meme.service
    content: |
      [Unit]
      Description=Meme service
      [Service]
      Type=oneshot
      WorkingDirectory=/root/memewebsite
      ExecStart=gunicorn -w 4 'main:app' -b 0.0.0.0:80
      User=root
      Environment="SESSION_KEY=${session_encoder_key}"
  - path: /tmp/db_init.sql
    content: | 
      CREATE USER ${username} WITH PASSWORD '${password}';
      CREATE DATABASE meme WITH OWNER ${username};
      \c meme;
      CREATE TABLE users (
      username VARCHAR(25) NOT NULL,
      password VARCHAR(32) NOT NULL,
      email VARCHAR(50) NOT NULL,
      admin BOOLEAN,
      PRIMARY KEY (username)
  );

  CREATE TABLE posts (
      post_id SERIAL,
      title VARCHAR(50) NOT NULL,
      url VARCHAR(255) NOT NULL,
      published INT NOT NULL,
      username VARCHAR(25) NOT NULL,
      approver VARCHAR(25),
      tag_all BOOLEAN,
      tag_emk BOOLEAN,
      tag_gpk BOOLEAN,
      tag_epk BOOLEAN,
      tag_vbk BOOLEAN,
      tag_vik BOOLEAN,
      tag_kjk BOOLEAN,
      tag_ttk BOOLEAN,
      tag_gtk BOOLEAN,
      FOREIGN KEY (username) REFERENCES users(username),
      FOREIGN KEY (approver) REFERENCES users(username),
    PRIMARY KEY (post_id)
  );

  CREATE TABLE votes (
    post_id INT NOT NULL,
    username VARCHAR(25) NOT NULL,
    vote SMALLINT NOT NULL CHECK (vote IN (-1, 1)),
    FOREIGN KEY (post_id) REFERENCES posts(post_id),
    FOREIGN KEY (username) REFERENCES users(username)
  );

  CREATE TABLE pending_registrations (
      email VARCHAR(40) NOT NULL,
      uuid VARCHAR(36) NOT NULL,
    username VARCHAR(25) NOT NULL,
      password VARCHAR(32) NOT NULL,
      Created INT NOT NULL,
      PRIMARY KEY (email)
  );

runcmd:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends postgresql-16
  #- sudo -u postgres psql -c "CREATE USER ${username} WITH PASSWORD '${password}';"
  #- sudo -u postgres psql -c "CREATE DATABASE meme WITH OWNER ${username};"
  - sudo -u postgres psql -f /tmp/db_init.sql

  - apt-get -y install pip python3-flask python3-flask-limiter python3-psycopg2 python3-boto3 python3-gunicorn gunicorn
  - cd /root && git clone https://github.com/tatliHU/memewebsite.git
  - find static -type f -exec sed -i 's/localhost:5000/bme.lol/g' {} +
  - find templates -type f -exec sed -i 's/localhost:5000/bme.lol/g' {} +
  - systemctl daemon-reload
  - systemctl enable meme
  - systemctl start meme

package_update: true
package_upgrade: true
packages:
  - git