#cloud-config

apt:
  sources:
    postgresql.list:
      source: "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main"
      keyid: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

write_files:
  - path: /etc/environment
    content: |
      SESSION_KEY=${session_encoder_key}
    append: true
  - path: /tmp/db_init.sql
    content: | 
      CREATE TABLE USERS (
          UserName VARCHAR(25) NOT NULL,
          Password VARCHAR(32) NOT NULL,
          Email VARCHAR(50) NOT NULL,
          EmailVerified BOOLEAN NOT NULL,
        Admin BOOLEAN,
          PRIMARY KEY (UserName)
      );

      CREATE TABLE POSTS (
          PostID SERIAL,
          Title VARCHAR(50) NOT NULL,
          Url VARCHAR(255) NOT NULL,
          Published INT NOT NULL,
          UserName VARCHAR(25) NOT NULL,
          Approver VARCHAR(25),
          FOREIGN KEY (UserName) REFERENCES users(UserName),
          FOREIGN KEY (Approver) REFERENCES users(UserName),
        PRIMARY KEY (PostID)
      );

      CREATE TABLE VOTES (
        PostID INT NOT NULL,
        UserName VARCHAR(25) NOT NULL,
        Vote SMALLINT NOT NULL CHECK (Vote IN (-1, 1)),
        FOREIGN KEY (PostID) REFERENCES posts(PostID),
        FOREIGN KEY (UserName) REFERENCES users(UserName)
      );

      CREATE TABLE EMAILS (
          EmailUUID VARCHAR(36) NOT NULL,
        UserName VARCHAR(25) NOT NULL,
        FOREIGN KEY (UserName) REFERENCES users(UserName),
          PRIMARY KEY (EmailUUID)
      );

runcmd:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends postgresql-16
  - sudo -u postgres psql -c "CREATE USER ${username} WITH PASSWORD '${password}';"
  - sudo -u postgres psql -c "CREATE DATABASE MEME WITH OWNER ${username};"
  - sudo -u postgres psql -f /tmp/db_init.sql

  - apt-get -y install pip python3-flask python3-psycopg2 python3-boto3 python3-gunicorn gunicorn
  - git clone https://github.com/tatliHU/memewebsite.git
  - export SESSION_KEY=${session_encoder_key} && cd memewebsite && gunicorn -w 4 'main:app' -b 0.0.0.0:80

package_update: true
package_upgrade: true
packages:
  - git